#!/bin/bash
# Made with ✨ Magic ©️ Nur Mukhammad Agus (https://github.com/madfxr), 2024. Free and Open Source Software (FOSS)

printf "\n\e[1;36m\e[5m          ようこそ\e[0m\e[1;36m\e[0m\n"
printf "███╗   ██╗███████╗ ██████╗\n"
printf "████╗  ██║██╔════╝██╔═══██╗\n"
printf "██╔██╗ ██║█████╗  ██║   ██║\n"
printf "██║╚██╗██║██╔══╝  ██║   ██║\n"
printf "██║ ╚████║███████╗╚██████╔╝\n"
printf "╚═╝  ╚═══╝╚══════╝ ╚═════╝\n"
printf "\e[1;36m- NETWORK MANAGEMENT TOOLS -\e[0m\n"

print_menu() {
    printf "\n\e[4m\e[1;36mMENU\e[0m\n"
    printf "N. Network List\n"
    printf "R. Router List\n"
    printf "P. Port List\n"
    printf "1. Disable Router\n"
    printf "2. Enable Router\n"
    printf "3. Disable Port\n"
    printf "4. Enable Port\n"
    printf "X. Exit\n"
}

while true; do
    print_menu
    read -rp $'\e[1;33mENTER MENU: \e[0m' option

    case $option in
        N|n)
            read -rp $'\e[1;33mINSERT PROJECT ID: \e[0m' project_id
            printf "[INFORMATION] Network List for Project ID \e[1;36m%s\e[0m\n" "$project_id"
            openstack network list --os-project-id "$project_id" --fit-width
            ;;
        R|r)
            read -rp $'\e[1;33mINSERT PROJECT ID: \e[0m' project_id
            printf "[INFORMATION] Router List for Project ID \e[1;36m%s\e[0m\n" "$project_id"
            openstack router list --os-project-id "$project_id" --fit-width
            ;;
        P|p)
            read -rp $'\e[1;33mINSERT PROJECT ID: \e[0m' project_id
            printf "[INFORMATION] Router List for Project ID \e[1;36m%s\e[0m\n" "$project_id"
            openstack router list --os-project-id "$project_id" --fit-width
            read -rp $'\e[1;33mINSERT ROUTER ID: \e[0m' router_id
            printf "[INFORMATION] Port List for Router ID \e[1;36m%s\e[0m for Project ID \e[1;36m%s\e[0m\n" "$router_id" "$project_id"
            openstack port list --os-project-id "$project_id" --router "$router_id" --fit-width
            ;;
        1)
            read -rp $'\e[1;33mINSERT PROJECT ID: \e[0m' project_id
            printf "[INFORMATION] List of Floating IP for Project ID \e[1;36m%s\e[0m\n" "$project_id"
            openstack server list --os-project-id "$project_id" -c Name -c Networks --fit-width
            read -rp $'\e[1;33mINSERT FLOATING IP: \e[0m' floating_ip
            printf "[BEFORE] Router List for Project ID \e[1;36m%s\e[0m\n" "$project_id"
            openstack router list --os-project-id "$project_id" --fit-width
            printf "[BEFORE] Ping from Floating IP %s \e[1;36m%s\e[0m\n" "$floating_ip"
            ping -c7 "$floating_ip"
            read -rp $'\e[1;33mINSERT ROUTER ID: \e[0m' router_id
            printf "[COMPLETED] Disable Router ID \e[1;36m%s\e[0m for Project ID \e[1;36m%s\e[0m\n" "$router_id" "$project_id"
            openstack router set --disable "$router_id" --os-project-id "$project_id"
            printf "[AFTER] Router List for Project ID \e[1;36m%s\e[0m\n" "$project_id"
            openstack router list --os-project-id "$project_id" --fit-width
            printf "[AFTER] Ping from Floating IP %s \e[1;36m%s\e[0m\n" "$floating_ip"
            ping -c7 "$floating_ip"
            ;;
        2)
            read -rp $'\e[1;33mINSERT PROJECT ID: \e[0m' project_id
            printf "[INFORMATION] List of Floating IP for Project ID \e[1;36m%s\e[0m\n" "$project_id"
            openstack server list --os-project-id "$project_id" -c Name -c Networks --fit-width
            read -rp $'\e[1;33mINSERT FLOATING IP: \e[0m' floating_ip
            printf "[BEFORE] Router List for Project ID \e[1;36m%s\e[0m\n" "$project_id"
            openstack router list --os-project-id "$project_id" --fit-width
            printf "[BEFORE] Ping from Floating IP %s \e[1;36m%s\e[0m\n" "$floating_ip"
            ping -c7 "$floating_ip"
            read -rp $'\e[1;33mINSERT ROUTER ID: \e[0m' router_id
            printf "[COMPLETED] Enable Router ID \e[1;36m%s\e[0m for Project ID \e[1;36m%s\e[0m\n" "$router_id" "$project_id"
            openstack router set --enable "$router_id" --os-project-id "$project_id"
            printf "[AFTER] Router List for Project ID \e[1;36m%s\e[0m\n" "$project_id"
            openstack router list --os-project-id "$project_id" --fit-width
            printf "[AFTER] Ping from Floating IP %s \e[1;36m%s\e[0m\n" "$floating_ip"
            ping -c7 "$floating_ip"
            ;;
        3)
            read -rp $'\e[1;33mINSERT PROJECT ID: \e[0m' project_id
            printf "[INFORMATION] List of Floating IP for Project ID \e[1;36m%s\e[0m\n" "$project_id"
            openstack server list --os-project-id "$project_id" -c Name -c Networks --fit-width
            read -rp $'\e[1;33mINSERT FLOATING IP: \e[0m' floating_ip
            printf "[INFORMATION] Router List for Project ID \e[1;36m%s\e[0m\n" "$project_id"
            openstack router list --os-project-id "$project_id" --fit-width
            read -rp $'\e[1;33mINSERT ROUTER ID: \e[0m' router_id
            printf "[BEFORE] Port List for Router ID \e[1;36m%s\e[0m for Project ID \e[1;36m%s\e[0m\n" "$router_id" "$project_id"
            openstack port list --os-project-id "$project_id" --router "$router_id" --fit-width
            printf "[BEFORE] Ping from Floating IP %s \e[1;36m%s\e[0m\n" "$floating_ip"
            ping -c7 "$floating_ip"
            read -rp $'\e[1;33mINSERT PORT ID: \e[0m' port_id
            printf "[COMPLETED] Disable Port ID \e[1;36m%s\e[0m for Router ID \e[1;36m%s\e[0m\n" "$port_id" "$router_id"
            openstack port set --disable "$port_id" --os-project-id "$project_id"
            printf "[AFTER] Port List for Router ID \e[1;36m%s\e[0m for Project ID \e[1;36m%s\e[0m\n" "$router_id" "$project_id"
            openstack port list --os-project-id "$project_id" --router "$router_id" --fit-width
            printf "[AFTER] Ping from Floating IP %s \e[1;36m%s\e[0m\n" "$floating_ip"
            ping -c7 "$floating_ip"
            ;;
        4)
            read -rp $'\e[1;33mINSERT PROJECT ID: \e[0m' project_id
            printf "[INFORMATION] List of Floating IP for Project ID \e[1;36m%s\e[0m\n" "$project_id"
            openstack server list --os-project-id "$project_id" -c Name -c Networks --fit-width
            read -rp $'\e[1;33mINSERT FLOATING IP: \e[0m' floating_ip
            printf "[INFORMATION] Router List for Project ID \e[1;36m%s\e[0m\n" "$project_id"
            openstack router list --os-project-id "$project_id" --fit-width
            read -rp $'\e[1;33mINSERT ROUTER ID: \e[0m' router_id
            printf "[BEFORE] Port List for Router ID \e[1;36m%s\e[0m for Project ID \e[1;36m%s\e[0m\n" "$router_id" "$project_id"
            openstack port list --os-project-id "$project_id" --router "$router_id" --fit-width
            printf "[BEFORE] Ping from Floating IP %s \e[1;36m%s\e[0m\n" "$floating_ip"
            ping -c7 "$floating_ip"
            read -rp $'\e[1;33mINSERT PORT ID: \e[0m' port_id
            printf "[COMPLETED] Enable Port ID \e[1;36m%s\e[0m for Router ID \e[1;36m%s\e[0m\n" "$port_id" "$router_id"
            openstack port set --enable "$port_id" --os-project-id "$project_id"
            printf "[AFTER] Port List for Router ID \e[1;36m%s\e[0m for Project ID \e[1;36m%s\e[0m\n" "$router_id" "$project_id"
            openstack port list --os-project-id "$project_id" --router "$router_id" --fit-width
            printf "[AFTER] Ping from Floating IP %s \e[1;36m%s\e[0m\n" "$floating_ip"
            ping -c7 "$floating_ip"
            ;;
        X|x)
            printf "\e[1;31m[INFORMATION] Exit from NEO Network Management Tools!\e[0m\n"
            exit 0
            ;;
        *)
            printf "\e[1;31m[ERROR] Invalid Option, Please Try Again!!\e[0m\n"
            ;;
    esac
done
